name: Test Yahoo Finance API Connection

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test-connection:
    name: Test Yahoo Finance API Connection - Get Exchange Rate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
          node-version-file: src/package.json
          cache: "npm"
          cache-dependency-path: src/package-lock.json

    - name: Install codebase dependencies
      working-directory: src/
      run: npm ci  # 👈 npm equivalent of yarn install --frozen-lockfile
    
    - name: Build codebase
      working-directory: src/
      run: npm run build

    - name: Run Yahoo Finance Test
      working-directory: website/src/maisvalias-tool
      run: node tests/test-yahoo-finance.js